name: fetch-commit-dates

on:
  push:
    branches:
      - main
    paths-ignore:
      - '_data/commit_dates.json'

jobs:

  update-file-dates:
    if: ${{ !startsWith(github.event.head_commit.committer.name, 'GitHub Actions') }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required to get full commit history
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Set the Ruby version
        
    - name: Run Ruby script
      run: ruby fetch-commit-dates.rb

    - name: Check for changes
      id: git-status
      run: |
        if git diff --quiet; then
          echo "changes_detected=false" >> "$GITHUB_OUTPUT"
        else
          echo "changes_detected=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Create branch
      if: steps.git-status.outputs.changes_detected == 'true'
      run: |
        git checkout -b "update-file-dates-${GITHUB_SHA}"
        
    - name: Commit changes
      if: steps.git-status.outputs.changes_detected == 'true'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add _data/commit_dates.json
        git commit -m "Update file dates"
        
    - name: Push changes
      if: steps.git-status.outputs.changes_detected == 'true'
      uses: ad-m/github-push-action@master
      with:
        branch: update-file-dates-${GITHUB_SHA}
        force: false  # Do not trigger an error if there are no changes to push
        
    - name: Create pull request
      if: steps.git-status.outputs.changes_detected == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: "Update file dates"
        title: "Update file dates"
        branch: "update-file-dates-${GITHUB_SHA}"
        base: main