name: fetch-commit-dates

on:
  push:
    branches:
      - main
    paths-ignore:
      - '_data/commit_dates.json'

jobs:

  update-last-commit:
    if: ${{ !startsWith(github.event.head_commit.committer.name, 'GitHub Actions') }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required to get full commit history
    
    - name: Update last commit dates
      run: |
        git checkout ${{ github.ref }}
        git log --pretty=format:"%ad|%H|%f" --date=iso --name-only | sort -u > last_commits.txt
        
        ruby -e "
          require 'json'
          require 'fileutils'

          # Create _data folder if it doesn't exist
          data_folder = '_data'
          Dir.mkdir(data_folder) unless File.exists?(data_folder)

          last_commits = {}
          `git ls-files -- '*.md'`.each_line do |file|
            file.chomp!
            commit_date = `git log -1 --format='%ad' --date=iso -- "#{file}"`.chomp
            last_commits[file] = commit_date
          end

          File.write(File.join(data_folder, 'commit_dates.json'), JSON.generate(last_commits))
        "
        
    - name: Commit last commit data
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add _data/commit_dates.json
        git commit -m "Update last commit dates"
        git push
