name: fetch-commit-dates

on:
  push:
    branches:
      - main
    paths-ignore:
      - '_data/commit_dates.json'

jobs:

  update-last-commit:
    if: ${{ !startsWith(github.event.head_commit.committer.name, 'GitHub Actions') }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required to get full commit history
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Set the Ruby version
        
    - name: Run Ruby script
      run: ruby fetch-commit-dates.rb
        
    - name: Commit last commit data
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add _data/commit_dates.json
        git commit -m "Update last commit dates"
        git push
