name: update-last-modified-dates

on:
  push:
    branches:
      - main
    paths-ignore:
      - '_data/last_commits.json'

jobs:

  update-last-commit:
    if: ${{ !startsWith(github.event.head_commit.committer.name, 'GitHub Actions') }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required to get full commit history
    
    - name: Update last commit dates
      run: |
        git checkout ${{ github.ref }}
        git log --pretty=format:"%ad|%H|%f" --date=iso --name-only | sort -u > last_commits.txt
        
        ruby -e "
         require 'json'

          last_commits = {}
          `git ls-tree -r --name-only HEAD`.each_line do |file|
            file.chomp!
            next unless file.end_with?('.md') # Filter only Markdown files
            
            # Escape special characters in file paths
            #file = file.gsub('"', '\"') # Escape double quotes
            
            commit_date = `git log -1 --format='%ad' --date=iso -- "#{file}"`.chomp
            last_commits[file] = commit_date
          end

          File.write('_data/last_commits.json', last_commits.to_json)
        "
        
    - name: Commit last commit data
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add _data/last_commits.json
        git commit -m "Update last commit data"
        git push
